[package]
name = "proto"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitcode.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "sync"] }
